# Exercise 4.8

### Contents

1. Aggregate mean of “order_number” grouped by “department_id”
2. Create a Loyalty Flag
3. Are the prices of products purchased by loyal customers different from those purchased by regular or new customers?
4. Targeting different spenders in marketing campaigns
5. Frequent vs. Non-Frequent Customers

## Importing Libraries and data

In [1]:
# importing libraries
import pandas as pd
import numpy as np
import os

In [2]:
#importing data using path shortcut
path1 = r'/Users/elysegross/Documents/Data Analytics/A4 - Instacart Basket Analysis/'
df_ords_prods_merged = pd.read_pickle(os.path.join(path1, '02 Data', 'Prepared Data', 'orders_products_ex4.7.pkl'))

In [3]:
df_ords_prods_merged.head()

,Unnamed: 0_x,Unnamed: 0.1,order_id,user_id,order_number,orders_day_of_week,order_hour,days_since_prior_order,product_id,add_to_cart_order,...,Unnamed: 0_y,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day
0,0,0,2539329,1,1,2,8,11.11484,196,1,...,195,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Average orders
1,1,1,2398795,1,2,3,7,15.00000,196,1,...,195,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Fewest orders
2,2,2,473747,1,3,3,12,21.00000,196,1,...,195,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Most orders
3,3,3,2254736,1,4,4,7,29.00000,196,1,...,195,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Fewest orders
4,4,4,431534,1,5,4,15,28.00000,196,1,...,195,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Most orders

## Step 2. Aggregating mean of "order_number" grouped by "department_id" for entire dataframe

In [4]:
#Using groupby function - nothing visible happens in this step
df_ords_prods_merged.groupby('product_name')

In [5]:
df_ords_prods_merged.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.457687
2                17.277920
3                17.179756
4                17.811403
5                15.215751
6                16.439806
7                17.225773
8                15.340520
9                15.895474
10               20.197148
11               16.170371
12               15.887622
13               16.583304
14               16.759763
15               16.165037
16               17.663250
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

## Step 3. Analyze the above result

The result is different from the subset because each of the average are different than those we saw previously on the subset. We see they can vary by up to 3 orders.

## Step 4. Create the Loyalty Flag

Creating a loyalty flag for the data
A loyal customer is one that comes back time and time again.

#### How we will determine loyalty:

Customer has > 40 max orders - "Loyal customer"
Cutsomer has 10 > 40 max orders - "Regular customer"
Customer has < 10 orders - "New customer"

The criteria for flags is often provided by the client

In [6]:
df_ords_prods_merged['max_order'] = df_ords_prods_merged.groupby(['user_id'])['order_number'].transform(np.max)

In [7]:
df_ords_prods_merged.size

713526660

In [8]:
# To allow us to see as many rows as we want
pd.options.display.max_rows = None

In [9]:
#Viewing the new dataframe 
df_ords_prods_merged.head(100)

,Unnamed: 0_x,Unnamed: 0.1,order_id,user_id,order_number,orders_day_of_week,order_hour,days_since_prior_order,product_id,add_to_cart_order,...,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order
0,0,0,2539329,1,1,2,8,11.11484,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Average orders,10
1,1,1,2398795,1,2,3,7,15.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Fewest orders,10
2,2,2,473747,1,3,3,12,21.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Most orders,10
3,3,3,2254736,1,4,4,7,29.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Fewest orders,10
4,4,4,431534,1,5,4,15,28.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Most orders,10
5,5,5,3367565,1,6,2,7,19.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Fewest orders,10
6,6,6,550135,1,7,1,9,20.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Busiest day,Average orders,10
7,7,7,3108588,1,8,1,14,14.00000,196,2,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Busiest day,Most orders,10
8,8,8,2295261,1,9,1,16,0.00000,196,4,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Busiest day,Most orders,10
9,9,9,2550362,1,10,4,8,30.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Average orders,10
10,144,144,2968173,15,15,1,9,7.00000,196,2,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Busiest day,Average orders,22
11,146,146,1870022,15,17,2,16,8.00000,196,6,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Most orders,22
12,147,147,1911383,15,18,2,11,7.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Most orders,22
13,150,150,2715276,15,21,1,9,7.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Busiest day,Average orders,22
14,151,151,487368,15,22,1,10,14.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Busiest day,Average orders,22
15,209,209,2293453,19,2,5,14,6.00000,196,3,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Least Busy,Most orders,9
16,212,212,1973799,19,5,6,12,8.00000,196,15,...,Soda,77,7,9.0,both,Mid-range product,Least busy,Least busy,Most orders,9
17,214,214,532817,19,7,4,17,6.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Most orders,9
18,232,232,1573906,21,10,3,10,6.00000,196,2,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Average orders,33
19,458,458,1593000,31,10,3,8,7.00000,196,17,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Average orders,20
20,465,465,2231262,31,17,3,11,8.00000,196,14,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Most orders,20
21,617,617,2580647,43,6,4,16,4.00000,196,9,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Most orders,11
22,620,620,2187180,43,9,4,12,3.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Most orders,11
23,751,751,2497897,52,1,1,9,11.11484,196,4,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Busiest day,Average orders,27
24,752,752,1318871,52,2,1,10,7.00000,196,5,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Busiest day,Average orders,27
25,753,753,1261384,52,3,1,10,7.00000,196,3,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Busiest day,Average orders,27
26,755,755,580568,52,5,2,10,8.00000,196,6,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Average orders,27
27,757,757,2428073,52,7,2,7,8.00000,196,5,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Fewest orders,27
28,759,759,342306,52,9,1,11,7.00000,196,5,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Busiest day,Most orders,27
29,760,760,1520353,52,10,2,10,8.00000,196,4,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Average orders,27
30,761,761,2542086,52,11,2,9,7.00000,196,3,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Average orders,27
31,762,762,944694,52,12,1,16,6.00000,196,7,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Busiest day,Most orders,27
32,765,765,1268191,52,15,2,11,8.00000,196,3,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Most orders,27
33,767,767,1122089,52,17,2,10,6.00000,196,4,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Average orders,27
34,768,768,1498922,52,18,2,10,14.00000,196,6,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Average orders,27
35,769,769,180919,52,19,3,8,8.00000,196,4,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Average orders,27
36,771,771,2695875,52,21,5,10,30.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Least Busy,Average orders,27
37,1022,1022,3205960,67,1,3,11,11.11484,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Most orders,24
38,1023,1023,970922,67,2,1,15,5.00000,196,2,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Busiest day,Most orders,24
39,1024,1024,596585,67,3,1,13,7.00000,196,2,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Busiest day,Most orders,24
40,1025,1025,2037087,67,4,2,9,8.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Average orders,24
41,1026,1026,2474111,67,5,3,14,8.00000,196,2,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Most orders,24
42,1027,1027,1568481,67,6,3,12,7.00000,196,2,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Most orders,24
43,1029,1029,2048527,67,8,2,11,7.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Most orders,24
44,1030,1030,2389031,67,9,2,14,7.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Most orders,24
45,1031,1031,2378562,67,10,1,10,6.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Busiest day,Average orders,24
46,1032,1032,1515698,67,11,1,11,7.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Busiest day,Most orders,24
47,1033,1033,1928050,67,12,2,12,8.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Most orders,24
48,1034,1034,1949274,67,13,1,10,6.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Busiest day,Average orders,24
49,1035,1035,551869,67,14,1,9,7.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Busiest day,Average orders,24
50,1037,1037,768572,67,16,4,10,9.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Average orders,24
51,1039,1039,150528,67,18,5,16,4.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Least Busy,Most orders,24
52,1040,1040,29758,67,19,0,14,9.00000,196,2,...,Soda,77,7,9.0,both,Mid-range product,Busiest day,Busiest day,Most orders,24
53,1042,1042,1558976,67,21,1,9,5.00000,196,2,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Busiest day,Average orders,24
54,1043,1043,863974,67,22,1,11,14.00000,196,3,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Busiest day,Most orders,24
55,1044,1044,2308399,67,23,1,14,14.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Busiest day,Most orders,24
56,1202,1202,2759128,81,3,1,9,14.00000,196,2,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Busiest day,Average orders,7
57,1204,1204,1812985,81,5,2,20,30.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Average orders,7
58,1208,1208,1889835,82,1,3,15,11.11484,196,6,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Most orders,19
59,1210,1210,499460,82,3,5,10,5.00000,196,2,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Least Busy,Average orders,19
60,1211,1211,2728456,82,4,0,11,16.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Busiest day,Busiest day,Most orders,19
61,1213,1213,2653743,82,6,4,9,13.00000,196,5,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Average orders,19
62,1216,1216,1358880,82,9,1,10,30.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Busiest day,Average orders,19
63,1217,1217,343588,82,10,2,11,1.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Most orders,19
64,1222,1222,3034663,82,15,2,11,12.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Most orders,19
65,1225,1225,147262,82,18,1,13,7.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Busiest day,Most orders,19
66,1226,1226,3144004,82,19,2,15,8.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Most orders,19
67,1480,1480,2126069,98,3,0,9,25.00000,196,7,...,Soda,77,7,9.0,both,Mid-range product,Busiest day,Busiest day,Average orders,14
68,1484,1484,2210120,98,7,5,14,5.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Least Busy,Most orders,14
69,1486,1486,681011,98,9,3,9,30.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Average orders,14
70,1488,1488,2846344,98,11,4,13,15.00000,196,2,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Most orders,14
71,1489,1489,747431,98,12,6,13,30.00000,196,4,...,Soda,77,7,9.0,both,Mid-range product,Least busy,Least busy,Most orders,14
72,1490,1490,2383054,98,13,4,11,30.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Most orders,14
73,1491,1491,1993729,98,14,5,8,8.00000,196,2,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Least Busy,Average orders,14
74,1608,1608,1403849,109,3,3,17,9.00000,196,5,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Most orders,6
75,1744,1744,520620,120,1,3,11,11.11484,196,2,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Most orders,3
76,1746,1746,3273029,120,3,2,8,19.00000,196,2,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Average orders,3
77,2781,2781,1861943,185,2,1,12,25.00000,196,10,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Busiest day,Most orders,6
78,2891,2891,2040988,195,1,1,14,11.11484,196,2,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Busiest day,Most orders,58
79,2898,2898,1680569,195,8,1,9,4.00000,196,2,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Busiest day,Average orders,58
80,2909,2909,276171,195,19,5,11,3.00000,196,2,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Least Busy,Most orders,58
81,2912,2912,2744976,195,22,5,10,7.00000,196,2,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Least Busy,Average orders,58
82,2915,2915,2781919,195,25,1,14,4.00000,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Busiest day,Most orders,58
83,2921,2921,1738718,195,31,2,8,4.00000,196,2,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Average orders,58
84,2924,2924,3058369,195,34,3,10,6.00000,196,2,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Average orders,58
85,2927,2927,1485596,195,37,2,15,0.00000,196,2,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Most orders,58
86,2930,2930,417035,195,40,3,16,2.00000,196,2,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Most orders,58
87,2937,2937,1615297,195,47,5,10,2.00000,196,2,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Least Busy,Average orders,58
88,2942,2942,1765587,195,52,3,12,2.00000,196,3,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Most orders,58
89,2947,2947,745908,195,57,4,11,3.00000,196,3,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Most orders,58
90,3451,3451,2505656,222,17,2,12,1.00000,196,2,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Most orders,70
91,3472,3472,3268370,222,38,5,15,1.00000,196,6,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Least Busy,Most orders,70
92,4667,4667,2016711,290,9,5,19,6.00000,196,8,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Least Busy,Average orders,51
93,4686,4686,2706088,290,28,6,10,7.00000,196,16,...,Soda,77,7,9.0,both,Mid-range product,Least busy,Least busy,Average orders,51
94,5551,5551,1952286,331,6,5,16,30.00000,196,8,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Least Busy,Most orders,8
95,5895,5895,3226575,360,1,5,12,11.11484,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Least Busy,Most orders,3
96,6137,6137,1469869,377,3,5,17,3.00000,196,9,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Least Busy,Most orders,3
97,6259,6259,1927023,387,2,4,10,22.00000,196,3,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Average orders,8
98,6740,6740,858092,420,4,1,19,30.00000,196,2,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Second Busiest day,Average orders,22
99,6741,6741,119314,420,5,3,19,16.00000,196,2,...,Soda,77,7,9.0,both,Mid-range product,Regular busy,Regular busy,Average orders,22

In [10]:
# Creating the loyalty labels in the column

df_ords_prods_merged.loc[df_ords_prods_merged['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'
df_ords_prods_merged.loc[(df_ords_prods_merged['max_order'] <= 40) & (df_ords_prods_merged['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'
df_ords_prods_merged.loc[df_ords_prods_merged['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [11]:
# Viewing only the columns we want to see with the 
    #new loyalty labels

df_ords_prods_merged[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0         1      New customer             1
1         1      New customer             2
2         1      New customer             3
3         1      New customer             4
4         1      New customer             5
5         1      New customer             6
6         1      New customer             7
7         1      New customer             8
8         1      New customer             9
9         1      New customer            10
10       15  Regular customer            15
11       15  Regular customer            17
12       15  Regular customer            18
13       15  Regular customer            21
14       15  Regular customer            22
15       19      New customer             2
16       19      New customer             5
17       19      New customer             7
18       21  Regular customer            10
19       31  Regular customer            10
20       31  Regular customer            17
21       43  Regular customer             6
22       43  Regular customer             9
23       52  Regular customer             1
24       52  Regular customer             2
25       52  Regular customer             3
26       52  Regular customer             5
27       52  Regular customer             7
28       52  Regular customer             9
29       52  Regular customer            10
30       52  Regular customer            11
31       52  Regular customer            12
32       52  Regular customer            15
33       52  Regular customer            17
34       52  Regular customer            18
35       52  Regular customer            19
36       52  Regular customer            21
37       67  Regular customer             1
38       67  Regular customer             2
39       67  Regular customer             3
40       67  Regular customer             4
41       67  Regular customer             5
42       67  Regular customer             6
43       67  Regular customer             8
44       67  Regular customer             9
45       67  Regular customer            10
46       67  Regular customer            11
47       67  Regular customer            12
48       67  Regular customer            13
49       67  Regular customer            14
50       67  Regular customer            16
51       67  Regular customer            18
52       67  Regular customer            19
53       67  Regular customer            21
54       67  Regular customer            22
55       67  Regular customer            23
56       81      New customer             3
57       81      New customer             5
58       82  Regular customer             1
59       82  Regular customer             3

## Step 5. Are the prices of products purchased by loyal customers different from those purchased by regular or new customers?

In [12]:
# Creating a smaller dataframe so it's easier to work with

df_prices = df_ords_prods_merged[['user_id', 'loyalty_flag', 'order_number', 'prices']]

In [13]:
# Confirming we have the desired columns

df_prices.head()

   user_id  loyalty_flag  order_number  prices
0        1  New customer             1     9.0
1        1  New customer             2     9.0
2        1  New customer             3     9.0
3        1  New customer             4     9.0
4        1  New customer             5     9.0

In [14]:
#Groupoing by loyalty flag to determine whether higher 
    #loyalty customers spending.
# Including muliple summary statistics to "check the 
    #basic statistics of product prices".
df_prices.groupby('loyalty_flag').agg({'prices': ['sum', 'mean', 'min', 'max']})

                        prices
                           sum       mean  min      max
loyalty_flag
Loyal customer    1.069370e+08  10.388854  1.0  99999.0
New customer      8.308000e+07  13.294634  1.0  99999.0
Regular customer  1.985738e+08  12.496419  1.0  99999.0

Though the loyal customers have spent more over time (as we see in sum), we see they have slightly lower average spending accross products (as we see in mean).

## Step 6. Targeting different spenders in marketing campaigns.

### Create a spending flag for each user based on the average price accross all their orders.

#### Criteria:
   
mean of prices < 10 - "Low spender"
mean of prices >= 10 - "High spender"

In [1]:
df_ords_prods_merged['price_means'] = df_ords_prods_merged.groupby(['user_id'])['prices'].transform(np.mean)

NameError: name 'df_ords_prods_merged' is not defined

In [16]:
df_ords_prods_merged.head()

,Unnamed: 0_x,Unnamed: 0.1,order_id,user_id,order_number,orders_day_of_week,order_hour,days_since_prior_order,product_id,add_to_cart_order,...,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,price_means
0,0,0,2539329,1,1,2,8,11.11484,196,1,...,7,9.0,both,Mid-range product,Regular busy,Regular busy,Average orders,10,New customer,5.813559
1,1,1,2398795,1,2,3,7,15.00000,196,1,...,7,9.0,both,Mid-range product,Regular busy,Regular busy,Fewest orders,10,New customer,5.813559
2,2,2,473747,1,3,3,12,21.00000,196,1,...,7,9.0,both,Mid-range product,Regular busy,Regular busy,Most orders,10,New customer,5.813559
3,3,3,2254736,1,4,4,7,29.00000,196,1,...,7,9.0,both,Mid-range product,Regular busy,Regular busy,Fewest orders,10,New customer,5.813559
4,4,4,431534,1,5,4,15,28.00000,196,1,...,7,9.0,both,Mid-range product,Regular busy,Regular busy,Most orders,10,New customer,5.813559

In [17]:
# Creating the spending flags in the column

df_ords_prods_merged.loc[df_ords_prods_merged['price_means'] < 10, 'spender_type'] = 'Low Spender'
df_ords_prods_merged.loc[(df_ords_prods_merged['price_means'] >= 10), 'spender_type'] = 'High Spender'

In [18]:
# Viewing only the columsn we want to see with new 
    #spending labels.

df_ords_prods_merged[['user_id', 'price_means', 'spender_type']].head(60)

    user_id  price_means  spender_type
0         1     5.813559   Low Spender
1         1     5.813559   Low Spender
2         1     5.813559   Low Spender
3         1     5.813559   Low Spender
4         1     5.813559   Low Spender
5         1     5.813559   Low Spender
6         1     5.813559   Low Spender
7         1     5.813559   Low Spender
8         1     5.813559   Low Spender
9         1     5.813559   Low Spender
10       15    11.416667  High Spender
11       15    11.416667  High Spender
12       15    11.416667  High Spender
13       15    11.416667  High Spender
14       15    11.416667  High Spender
15       19     4.745098   Low Spender
16       19     4.745098   Low Spender
17       19     4.745098   Low Spender
18       21    17.263415  High Spender
19       31    11.735786  High Spender
20       31    11.735786  High Spender
21       43     6.687075   Low Spender
22       43     6.687075   Low Spender
23       52    14.254438  High Spender
24       52    14.254438  High Spender
25       52    14.254438  High Spender
26       52    14.254438  High Spender
27       52    14.254438  High Spender
28       52    14.254438  High Spender
29       52    14.254438  High Spender
30       52    14.254438  High Spender
31       52    14.254438  High Spender
32       52    14.254438  High Spender
33       52    14.254438  High Spender
34       52    14.254438  High Spender
35       52    14.254438  High Spender
36       52    14.254438  High Spender
37       67    12.419753  High Spender
38       67    12.419753  High Spender
39       67    12.419753  High Spender
40       67    12.419753  High Spender
41       67    12.419753  High Spender
42       67    12.419753  High Spender
43       67    12.419753  High Spender
44       67    12.419753  High Spender
45       67    12.419753  High Spender
46       67    12.419753  High Spender
47       67    12.419753  High Spender
48       67    12.419753  High Spender
49       67    12.419753  High Spender
50       67    12.419753  High Spender
51       67    12.419753  High Spender
52       67    12.419753  High Spender
53       67    12.419753  High Spender
54       67    12.419753  High Spender
55       67    12.419753  High Spender
56       81     4.592593   Low Spender
57       81     4.592593   Low Spender
58       82     9.961832   Low Spender
59       82     9.961832   Low Spender

## Step 7. Frequent vs. Non-frequent customers

#### Criteria:
   
median of days_since_prior_order > 20 - "Non-frequent customer"
median of days_since_prior_order 10 > 20 - "Regular customer"
median of days_since_prior_order <= 10 - "Frequent customer"

In [22]:
df_ords_prods_merged.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

In [23]:
# Viewing data
df_ords_prods_merged.head(100)

,Unnamed: 0_x,Unnamed: 0.1,order_id,user_id,order_number,orders_day_of_week,order_hour,days_since_prior_order,product_id,add_to_cart_order,...,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,price_means,spender_type,median_days_since_prior_order
0,0,0,2539329,1,1,2,8,11.11484,196,1,...,both,Mid-range product,Regular busy,Regular busy,Average orders,10,New customer,5.813559,Low Spender,20.00000
1,1,1,2398795,1,2,3,7,15.00000,196,1,...,both,Mid-range product,Regular busy,Regular busy,Fewest orders,10,New customer,5.813559,Low Spender,20.00000
2,2,2,473747,1,3,3,12,21.00000,196,1,...,both,Mid-range product,Regular busy,Regular busy,Most orders,10,New customer,5.813559,Low Spender,20.00000
3,3,3,2254736,1,4,4,7,29.00000,196,1,...,both,Mid-range product,Regular busy,Regular busy,Fewest orders,10,New customer,5.813559,Low Spender,20.00000
4,4,4,431534,1,5,4,15,28.00000,196,1,...,both,Mid-range product,Regular busy,Regular busy,Most orders,10,New customer,5.813559,Low Spender,20.00000
5,5,5,3367565,1,6,2,7,19.00000,196,1,...,both,Mid-range product,Regular busy,Regular busy,Fewest orders,10,New customer,5.813559,Low Spender,20.00000
6,6,6,550135,1,7,1,9,20.00000,196,1,...,both,Mid-range product,Regular busy,Second Busiest day,Average orders,10,New customer,5.813559,Low Spender,20.00000
7,7,7,3108588,1,8,1,14,14.00000,196,2,...,both,Mid-range product,Regular busy,Second Busiest day,Most orders,10,New customer,5.813559,Low Spender,20.00000
8,8,8,2295261,1,9,1,16,0.00000,196,4,...,both,Mid-range product,Regular busy,Second Busiest day,Most orders,10,New customer,5.813559,Low Spender,20.00000
9,9,9,2550362,1,10,4,8,30.00000,196,1,...,both,Mid-range product,Regular busy,Regular busy,Average orders,10,New customer,5.813559,Low Spender,20.00000
10,144,144,2968173,15,15,1,9,7.00000,196,2,...,both,Mid-range product,Regular busy,Second Busiest day,Average orders,22,Regular customer,11.416667,High Spender,10.55742
11,146,146,1870022,15,17,2,16,8.00000,196,6,...,both,Mid-range product,Regular busy,Regular busy,Most orders,22,Regular customer,11.416667,High Spender,10.55742
12,147,147,1911383,15,18,2,11,7.00000,196,1,...,both,Mid-range product,Regular busy,Regular busy,Most orders,22,Regular customer,11.416667,High Spender,10.55742
13,150,150,2715276,15,21,1,9,7.00000,196,1,...,both,Mid-range product,Regular busy,Second Busiest day,Average orders,22,Regular customer,11.416667,High Spender,10.55742
14,151,151,487368,15,22,1,10,14.00000,196,1,...,both,Mid-range product,Regular busy,Second Busiest day,Average orders,22,Regular customer,11.416667,High Spender,10.55742
15,209,209,2293453,19,2,5,14,6.00000,196,3,...,both,Mid-range product,Regular busy,Second Least Busy,Most orders,9,New customer,4.745098,Low Spender,7.00000
16,212,212,1973799,19,5,6,12,8.00000,196,15,...,both,Mid-range product,Least busy,Least busy,Most orders,9,New customer,4.745098,Low Spender,7.00000
17,214,214,532817,19,7,4,17,6.00000,196,1,...,both,Mid-range product,Regular busy,Regular busy,Most orders,9,New customer,4.745098,Low Spender,7.00000
18,232,232,1573906,21,10,3,10,6.00000,196,2,...,both,Mid-range product,Regular busy,Regular busy,Average orders,33,Regular customer,17.263415,High Spender,8.00000
19,458,458,1593000,31,10,3,8,7.00000,196,17,...,both,Mid-range product,Regular busy,Regular busy,Average orders,20,Regular customer,11.735786,High Spender,6.00000
20,465,465,2231262,31,17,3,11,8.00000,196,14,...,both,Mid-range product,Regular busy,Regular busy,Most orders,20,Regular customer,11.735786,High Spender,6.00000
21,617,617,2580647,43,6,4,16,4.00000,196,9,...,both,Mid-range product,Regular busy,Regular busy,Most orders,11,Regular customer,6.687075,Low Spender,10.00000
22,620,620,2187180,43,9,4,12,3.00000,196,1,...,both,Mid-range product,Regular busy,Regular busy,Most orders,11,Regular customer,6.687075,Low Spender,10.00000
23,751,751,2497897,52,1,1,9,11.11484,196,4,...,both,Mid-range product,Regular busy,Second Busiest day,Average orders,27,Regular customer,14.254438,High Spender,8.00000
24,752,752,1318871,52,2,1,10,7.00000,196,5,...,both,Mid-range product,Regular busy,Second Busiest day,Average orders,27,Regular customer,14.254438,High Spender,8.00000
25,753,753,1261384,52,3,1,10,7.00000,196,3,...,both,Mid-range product,Regular busy,Second Busiest day,Average orders,27,Regular customer,14.254438,High Spender,8.00000
26,755,755,580568,52,5,2,10,8.00000,196,6,...,both,Mid-range product,Regular busy,Regular busy,Average orders,27,Regular customer,14.254438,High Spender,8.00000
27,757,757,2428073,52,7,2,7,8.00000,196,5,...,both,Mid-range product,Regular busy,Regular busy,Fewest orders,27,Regular customer,14.254438,High Spender,8.00000
28,759,759,342306,52,9,1,11,7.00000,196,5,...,both,Mid-range product,Regular busy,Second Busiest day,Most orders,27,Regular customer,14.254438,High Spender,8.00000
29,760,760,1520353,52,10,2,10,8.00000,196,4,...,both,Mid-range product,Regular busy,Regular busy,Average orders,27,Regular customer,14.254438,High Spender,8.00000
30,761,761,2542086,52,11,2,9,7.00000,196,3,...,both,Mid-range product,Regular busy,Regular busy,Average orders,27,Regular customer,14.254438,High Spender,8.00000
31,762,762,944694,52,12,1,16,6.00000,196,7,...,both,Mid-range product,Regular busy,Second Busiest day,Most orders,27,Regular customer,14.254438,High Spender,8.00000
32,765,765,1268191,52,15,2,11,8.00000,196,3,...,both,Mid-range product,Regular busy,Regular busy,Most orders,27,Regular customer,14.254438,High Spender,8.00000
33,767,767,1122089,52,17,2,10,6.00000,196,4,...,both,Mid-range product,Regular busy,Regular busy,Average orders,27,Regular customer,14.254438,High Spender,8.00000
34,768,768,1498922,52,18,2,10,14.00000,196,6,...,both,Mid-range product,Regular busy,Regular busy,Average orders,27,Regular customer,14.254438,High Spender,8.00000
35,769,769,180919,52,19,3,8,8.00000,196,4,...,both,Mid-range product,Regular busy,Regular busy,Average orders,27,Regular customer,14.254438,High Spender,8.00000
36,771,771,2695875,52,21,5,10,30.00000,196,1,...,both,Mid-range product,Regular busy,Second Least Busy,Average orders,27,Regular customer,14.254438,High Spender,8.00000
37,1022,1022,3205960,67,1,3,11,11.11484,196,1,...,both,Mid-range product,Regular busy,Regular busy,Most orders,24,Regular customer,12.419753,High Spender,7.00000
38,1023,1023,970922,67,2,1,15,5.00000,196,2,...,both,Mid-range product,Regular busy,Second Busiest day,Most orders,24,Regular customer,12.419753,High Spender,7.00000
39,1024,1024,596585,67,3,1,13,7.00000,196,2,...,both,Mid-range product,Regular busy,Second Busiest day,Most orders,24,Regular customer,12.419753,High Spender,7.00000
40,1025,1025,2037087,67,4,2,9,8.00000,196,1,...,both,Mid-range product,Regular busy,Regular busy,Average orders,24,Regular customer,12.419753,High Spender,7.00000
41,1026,1026,2474111,67,5,3,14,8.00000,196,2,...,both,Mid-range product,Regular busy,Regular busy,Most orders,24,Regular customer,12.419753,High Spender,7.00000
42,1027,1027,1568481,67,6,3,12,7.00000,196,2,...,both,Mid-range product,Regular busy,Regular busy,Most orders,24,Regular customer,12.419753,High Spender,7.00000
43,1029,1029,2048527,67,8,2,11,7.00000,196,1,...,both,Mid-range product,Regular busy,Regular busy,Most orders,24,Regular customer,12.419753,High Spender,7.00000
44,1030,1030,2389031,67,9,2,14,7.00000,196,1,...,both,Mid-range product,Regular busy,Regular busy,Most orders,24,Regular customer,12.419753,High Spender,7.00000
45,1031,1031,2378562,67,10,1,10,6.00000,196,1,...,both,Mid-range product,Regular busy,Second Busiest day,Average orders,24,Regular customer,12.419753,High Spender,7.00000
46,1032,1032,1515698,67,11,1,11,7.00000,196,1,...,both,Mid-range product,Regular busy,Second Busiest day,Most orders,24,Regular customer,12.419753,High Spender,7.00000
47,1033,1033,1928050,67,12,2,12,8.00000,196,1,...,both,Mid-range product,Regular busy,Regular busy,Most orders,24,Regular customer,12.419753,High Spender,7.00000
48,1034,1034,1949274,67,13,1,10,6.00000,196,1,...,both,Mid-range product,Regular busy,Second Busiest day,Average orders,24,Regular customer,12.419753,High Spender,7.00000
49,1035,1035,551869,67,14,1,9,7.00000,196,1,...,both,Mid-range product,Regular busy,Second Busiest day,Average orders,24,Regular customer,12.419753,High Spender,7.00000
50,1037,1037,768572,67,16,4,10,9.00000,196,1,...,both,Mid-range product,Regular busy,Regular busy,Average orders,24,Regular customer,12.419753,High Spender,7.00000
51,1039,1039,150528,67,18,5,16,4.00000,196,1,...,both,Mid-range product,Regular busy,Second Least Busy,Most orders,24,Regular customer,12.419753,High Spender,7.00000
52,1040,1040,29758,67,19,0,14,9.00000,196,2,...,both,Mid-range product,Busiest day,Busiest day,Most orders,24,Regular customer,12.419753,High Spender,7.00000
53,1042,1042,1558976,67,21,1,9,5.00000,196,2,...,both,Mid-range product,Regular busy,Second Busiest day,Average orders,24,Regular customer,12.419753,High Spender,7.00000
54,1043,1043,863974,67,22,1,11,14.00000,196,3,...,both,Mid-range product,Regular busy,Second Busiest day,Most orders,24,Regular customer,12.419753,High Spender,7.00000
55,1044,1044,2308399,67,23,1,14,14.00000,196,1,...,both,Mid-range product,Regular busy,Second Busiest day,Most orders,24,Regular customer,12.419753,High Spender,7.00000
56,1202,1202,2759128,81,3,1,9,14.00000,196,2,...,both,Mid-range product,Regular busy,Second Busiest day,Average orders,7,New customer,4.592593,Low Spender,30.00000
57,1204,1204,1812985,81,5,2,20,30.00000,196,1,...,both,Mid-range product,Regular busy,Regular busy,Average orders,7,New customer,4.592593,Low Spender,30.00000
58,1208,1208,1889835,82,1,3,15,11.11484,196,6,...,both,Mid-range product,Regular busy,Regular busy,Most orders,19,Regular customer,9.961832,Low Spender,11.11484
59,1210,1210,499460,82,3,5,10,5.00000,196,2,...,both,Mid-range product,Regular busy,Second Least Busy,Average orders,19,Regular customer,9.961832,Low Spender,11.11484
60,1211,1211,2728456,82,4,0,11,16.00000,196,1,...,both,Mid-range product,Busiest day,Busiest day,Most orders,19,Regular customer,9.961832,Low Spender,11.11484
61,1213,1213,2653743,82,6,4,9,13.00000,196,5,...,both,Mid-range product,Regular busy,Regular busy,Average orders,19,Regular customer,9.961832,Low Spender,11.11484
62,1216,1216,1358880,82,9,1,10,30.00000,196,1,...,both,Mid-range product,Regular busy,Second Busiest day,Average orders,19,Regular customer,9.961832,Low Spender,11.11484
63,1217,1217,343588,82,10,2,11,1.00000,196,1,...,both,Mid-range product,Regular busy,Regular busy,Most orders,19,Regular customer,9.961832,Low Spender,11.11484
64,1222,1222,3034663,82,15,2,11,12.00000,196,1,...,both,Mid-range product,Regular busy,Regular busy,Most orders,19,Regular customer,9.961832,Low Spender,11.11484
65,1225,1225,147262,82,18,1,13,7.00000,196,1,...,both,Mid-range product,Regular busy,Second Busiest day,Most orders,19,Regular customer,9.961832,Low Spender,11.11484
66,1226,1226,3144004,82,19,2,15,8.00000,196,1,...,both,Mid-range product,Regular busy,Regular busy,Most orders,19,Regular customer,9.961832,Low Spender,11.11484
67,1480,1480,2126069,98,3,0,9,25.00000,196,7,...,both,Mid-range product,Busiest day,Busiest day,Average orders,14,Regular customer,6.200000,Low Spender,24.50000
68,1484,1484,2210120,98,7,5,14,5.00000,196,1,...,both,Mid-range product,Regular busy,Second Least Busy,Most orders,14,Regular customer,6.200000,Low Spender,24.50000
69,1486,1486,681011,98,9,3,9,30.00000,196,1,...,both,Mid-range product,Regular busy,Regular busy,Average orders,14,Regular customer,6.200000,Low Spender,24.50000
70,1488,1488,2846344,98,11,4,13,15.00000,196,2,...,both,Mid-range product,Regular busy,Regular busy,Most orders,14,Regular customer,6.200000,Low Spender,24.50000
71,1489,1489,747431,98,12,6,13,30.00000,196,4,...,both,Mid-range product,Least busy,Least busy,Most orders,14,Regular customer,6.200000,Low Spender,24.50000
72,1490,1490,2383054,98,13,4,11,30.00000,196,1,...,both,Mid-range product,Regular busy,Regular busy,Most orders,14,Regular customer,6.200000,Low Spender,24.50000
73,1491,1491,1993729,98,14,5,8,8.00000,196,2,...,both,Mid-range product,Regular busy,Second Least Busy,Average orders,14,Regular customer,6.200000,Low Spender,24.50000
74,1608,1608,1403849,109,3,3,17,9.00000,196,5,...,both,Mid-range product,Regular busy,Regular busy,Most orders,6,New customer,4.000000,Low Spender,20.00000
75,1744,1744,520620,120,1,3,11,11.11484,196,2,...,both,Mid-range product,Regular busy,Regular busy,Most orders,3,New customer,2.000000,Low Spender,15.00000
76,1746,1746,3273029,120,3,2,8,19.00000,196,2,...,both,Mid-range product,Regular busy,Regular busy,Average orders,3,New customer,2.000000,Low Spender,15.00000
77,2781,2781,1861943,185,2,1,12,25.00000,196,10,...,both,Mid-range product,Regular busy,Second Busiest day,Most orders,6,New customer,3.000000,Low Spender,25.00000
78,2891,2891,2040988,195,1,1,14,11.11484,196,2,...,both,Mid-range product,Regular busy,Second Busiest day,Most orders,58,Loyal customer,32.410811,High Spender,4.00000
79,2898,2898,1680569,195,8,1,9,4.00000,196,2,...,both,Mid-range product,Regular busy,Second Busiest day,Average orders,58,Loyal customer,32.410811,High Spender,4.00000
80,2909,2909,276171,195,19,5,11,3.00000,196,2,...,both,Mid-range product,Regular busy,Second Least Busy,Most orders,58,Loyal customer,32.410811,High Spender,4.00000
81,2912,2912,2744976,195,22,5,10,7.00000,196,2,...,both,Mid-range product,Regular busy,Second Least Busy,Average orders,58,Loyal customer,32.410811,High Spender,4.00000
82,2915,2915,2781919,195,25,1,14,4.00000,196,1,...,both,Mid-range product,Regular busy,Second Busiest day,Most orders,58,Loyal customer,32.410811,High Spender,4.00000
83,2921,2921,1738718,195,31,2,8,4.00000,196,2,...,both,Mid-range product,Regular busy,Regular busy,Average orders,58,Loyal customer,32.410811,High Spender,4.00000
84,2924,2924,3058369,195,34,3,10,6.00000,196,2,...,both,Mid-range product,Regular busy,Regular busy,Average orders,58,Loyal customer,32.410811,High Spender,4.00000
85,2927,2927,1485596,195,37,2,15,0.00000,196,2,...,both,Mid-range product,Regular busy,Regular busy,Most orders,58,Loyal customer,32.410811,High Spender,4.00000
86,2930,2930,417035,195,40,3,16,2.00000,196,2,...,both,Mid-range product,Regular busy,Regular busy,Most orders,58,Loyal customer,32.410811,High Spender,4.00000
87,2937,2937,1615297,195,47,5,10,2.00000,196,2,...,both,Mid-range product,Regular busy,Second Least Busy,Average orders,58,Loyal customer,32.410811,High Spender,4.00000
88,2942,2942,1765587,195,52,3,12,2.00000,196,3,...,both,Mid-range product,Regular busy,Regular busy,Most orders,58,Loyal customer,32.410811,High Spender,4.00000
89,2947,2947,745908,195,57,4,11,3.00000,196,3,...,both,Mid-range product,Regular busy,Regular busy,Most orders,58,Loyal customer,32.410811,High Spender,4.00000
90,3451,3451,2505656,222,17,2,12,1.00000,196,2,...,both,Mid-range product,Regular busy,Regular busy,Most orders,70,Loyal customer,41.035124,High Spender,5.00000
91,3472,3472,3268370,222,38,5,15,1.00000,196,6,...,both,Mid-range product,Regular busy,Second Least Busy,Most orders,70,Loyal customer,41.035124,High Spender,5.00000
92,4667,4667,2016711,290,9,5,19,6.00000,196,8,...,both,Mid-range product,Regular busy,Second Least Busy,Average orders,51,Loyal customer,25.252201,High Spender,7.00000
93,4686,4686,2706088,290,28,6,10,7.00000,196,16,...,both,Mid-range product,Least busy,Least busy,Average orders,51,Loyal customer,25.252201,High Spender,7.00000
94,5551,5551,1952286,331,6,5,16,30.00000,196,8,...,both,Mid-range product,Regular busy,Second Least Busy,Most orders,8,New customer,4.564103,Low Spender,30.00000
95,5895,5895,3226575,360,1,5,12,11.11484,196,1,...,both,Mid-range product,Regular busy,Second Least Busy,Most orders,3,New customer,2.000000,Low Spender,6.00000
96,6137,6137,1469869,377,3,5,17,3.00000,196,9,...,both,Mid-range product,Regular busy,Second Least Busy,Most orders,3,New customer,1.931034,Low Spender,11.11484
97,6259,6259,1927023,387,2,4,10,22.00000,196,3,...,both,Mid-range product,Regular busy,Regular busy,Average orders,8,New customer,4.050847,Low Spender,10.00000
98,6740,6740,858092,420,4,1,19,30.00000,196,2,...,both,Mid-range product,Regular busy,Second Busiest day,Average orders,22,Regular customer,10.664062,High Spender,8.00000
99,6741,6741,119314,420,5,3,19,16.00000,196,2,...,both,Mid-range product,Regular busy,Regular busy,Average orders,22,Regular customer,10.664062,High Spender,8.00000

In [25]:
# Creating the loyalty labels in the column

df_ords_prods_merged.loc[(df_ords_prods_merged['median_days_since_prior_order'] > 20)  & (df_ords_prods_merged['median_days_since_prior_order'] == 'NaN'), 'spending_flag'] = 'Non-frequent customer'
df_ords_prods_merged.loc[(df_ords_prods_merged['median_days_since_prior_order'] <= 20) & (df_ords_prods_merged['median_days_since_prior_order'] > 10), 'spending_flag'] = 'Regular customer'
df_ords_prods_merged.loc[(df_ords_prods_merged['median_days_since_prior_order'] <= 10), 'spending_flag'] = 'Frequent customer'

In [26]:
# Viewing only the columns we want to see with the 
    #new spending flags.

df_ords_prods_merged[['user_id', 'spending_flag', 'median_days_since_prior_order']].head(60)

    user_id      spending_flag  median_days_since_prior_order
0         1   Regular customer                       20.00000
1         1   Regular customer                       20.00000
2         1   Regular customer                       20.00000
3         1   Regular customer                       20.00000
4         1   Regular customer                       20.00000
5         1   Regular customer                       20.00000
6         1   Regular customer                       20.00000
7         1   Regular customer                       20.00000
8         1   Regular customer                       20.00000
9         1   Regular customer                       20.00000
10       15   Regular customer                       10.55742
11       15   Regular customer                       10.55742
12       15   Regular customer                       10.55742
13       15   Regular customer                       10.55742
14       15   Regular customer                       10.55742
15       19  Frequent customer                        7.00000
16       19  Frequent customer                        7.00000
17       19  Frequent customer                        7.00000
18       21  Frequent customer                        8.00000
19       31  Frequent customer                        6.00000
20       31  Frequent customer                        6.00000
21       43  Frequent customer                       10.00000
22       43  Frequent customer                       10.00000
23       52  Frequent customer                        8.00000
24       52  Frequent customer                        8.00000
25       52  Frequent customer                        8.00000
26       52  Frequent customer                        8.00000
27       52  Frequent customer                        8.00000
28       52  Frequent customer                        8.00000
29       52  Frequent customer                        8.00000
30       52  Frequent customer                        8.00000
31       52  Frequent customer                        8.00000
32       52  Frequent customer                        8.00000
33       52  Frequent customer                        8.00000
34       52  Frequent customer                        8.00000
35       52  Frequent customer                        8.00000
36       52  Frequent customer                        8.00000
37       67  Frequent customer                        7.00000
38       67  Frequent customer                        7.00000
39       67  Frequent customer                        7.00000
40       67  Frequent customer                        7.00000
41       67  Frequent customer                        7.00000
42       67  Frequent customer                        7.00000
43       67  Frequent customer                        7.00000
44       67  Frequent customer                        7.00000
45       67  Frequent customer                        7.00000
46       67  Frequent customer                        7.00000
47       67  Frequent customer                        7.00000
48       67  Frequent customer                        7.00000
49       67  Frequent customer                        7.00000
50       67  Frequent customer                        7.00000
51       67  Frequent customer                        7.00000
52       67  Frequent customer                        7.00000
53       67  Frequent customer                        7.00000
54       67  Frequent customer                        7.00000
55       67  Frequent customer                        7.00000
56       81                NaN                       30.00000
57       81                NaN                       30.00000
58       82   Regular customer                       11.11484
59       82   Regular customer                       11.11484

## Export the Data

In [27]:
# Export data to pickle file
df_ords_prods_merged.to_pickle(os.path.join(path1, '02 Data','Prepared Data', 'orders_products_ex4.8.pkl'))

# THE END!